// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC8CbMqmRjVhVtMQzGpV_k7Gi7TnjsNyQ',
    appId: '1:1057526336351:web:a5f5318c219798c7f344ea',
    messagingSenderId: '1057526336351',
    projectId: 'factory-tienda',
    authDomain: 'factory-tienda.firebaseapp.com',
    storageBucket: 'factory-tienda.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqEpEbg9PG3FmMraxtZq0izSe_gCWasTc',
    appId: '1:1057526336351:android:9cc3e294da6f6c91f344ea',
    messagingSenderId: '1057526336351',
    projectId: 'factory-tienda',
    storageBucket: 'factory-tienda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG6uKx46wL2JPsl7Uw1SLvPuFT4yLWQUM',
    appId: '1:1057526336351:ios:e2212788adba3c93f344ea',
    messagingSenderId: '1057526336351',
    projectId: 'factory-tienda',
    storageBucket: 'factory-tienda.firebasestorage.app',
    iosBundleId: 'com.example.appMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG6uKx46wL2JPsl7Uw1SLvPuFT4yLWQUM',
    appId: '1:1057526336351:ios:e2212788adba3c93f344ea',
    messagingSenderId: '1057526336351',
    projectId: 'factory-tienda',
    storageBucket: 'factory-tienda.firebasestorage.app',
    iosBundleId: 'com.example.appMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC8CbMqmRjVhVtMQzGpV_k7Gi7TnjsNyQ',
    appId: '1:1057526336351:web:3758d6907363f02bf344ea',
    messagingSenderId: '1057526336351',
    projectId: 'factory-tienda',
    authDomain: 'factory-tienda.firebaseapp.com',
    storageBucket: 'factory-tienda.firebasestorage.app',
  );
}
